# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

name: Verify the commit
run-name: ${{ github.actor }} is verifying the commit.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: rms
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5 

    steps:

      - name: check out branch
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clean
        run: mvn clean

      - name: Compile
        run: mvn compile

      - name: Run test suite
        run: mvn -DDATABASE_URL='jdbc:postgresql://localhost:5432/rms' -DDATABASE_USERNAME=postgres -DDATABASE_PASSWORD=postgres test

      - name: Build artifact
        run: mvn package -DskipTests install